service: dev-human-website

custom:
  staging:
    local_path: build/staging
    certificate: arn:aws:acm:us-east-1:033201381223:certificate/2cc611c2-8bbb-43f3-8409-8bb57aabbb96
    redirectToMainDomain: false
    domain:
      - staging.dev-human.io
  production:
    #local_path: build/production
    local_path: coming_soon
    certificate: arn:aws:acm:us-east-1:033201381223:certificate/f0e06be4-fd8e-409a-8acc-5d17be1cecee
    redirectToMainDomain: true
    domain:
      - dev-human.io
      - www.dev-human.io

provider:
  name: aws
  region: eu-central-1
  runtime: provided.al2
  deploymentMethod: direct
  stage: staging
  tags:
    project-name: dev-human-website
    repository: https://github.com/dev-human/dev-human
  stackTags:
    customer: dev-human

plugins:
  - serverless-lift

constructs:
  website:
    type: static-website
    errorPage: 404.html
    path: ${self:custom.${sls:stage}.local_path}
    certificate: ${self:custom.${sls:stage}.certificate}
    domain: ${self:custom.${sls:stage}.domain}
    redirectToMainDomain: ${self:custom.${sls:stage}.redirectToMainDomain}
