name: Deploy to staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7

      - name: Generate the website
        run: make build-staging

