name: Deploy to staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v1

      - name: Generate the website
        run: make build-staging

      - name: Deploy with Serverless
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless plugin install --name serverless-lift && serverless deploy --stage=staging --verbose"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1